### ISSUE TITLE
Search User: partial search not working

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#10]
Step 1: I have uploaded a student with 
first name: "Student 1"
Last name : "Name 1"

Step 2: I search user with type first name "Student" in search parameter and hit search

Issue: it is not giving me proper result, it  says "no data found"
Expected: it should shows the result whose first name starts with "Student"

Note: Same case is also with other search parameters eg last name, and others text fields.....

**Comment by manasghosh81** [comment]
The functionality of partial search is not present in FSD. This will be an enhancement.

**Comment by manasghosh81** [comment]
Hi Mayank,
This is done.

**Comment by mayank2k2** [comment]
partial search is working how ever Roll Number should not use partial search, is is numeric field, see my email below. 

Hi Manas,
This should be standard search behavior as per industry standard same as implemented for school search.
“Non-numeric text fields should have starts with  search behavior eg. If we put first name as may all the students having name start with may should be displayed in result.”  

Please let me know.

**Comment by mouparnadas** [comment]
This is now fixed.

**Comment by mayank2k2** [comment]
This is not fixed correctly, please review my comment earlier posted.
_**
"partial search is working how ever Roll Number should not use partial search, is is numeric field, see my email below."**_

**Comment by mouparnadas** [comment]
The suggested changes have been implemented. It will be available in next deployment.

**Comment by manasghosh81** [comment]
This fix is available in UAT. Please recheck this

**Comment by mayank2k2** [comment]
working
