### ISSUE TITLE
Student Promotion not working

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#29]
![promotion not working](https://cloud.githubusercontent.com/assets/16239450/12843680/f3aa3256-cc20-11e5-8b55-73d3851b9f2e.JPG)

I exported the student data and change the class 3 to 5 and try to validate no error / no status, doesn't know what happen

**Comment by manasghosh81** [comment]
Working on this.

**Comment by mayank2k2** [comment]
This is not working

**Comment by mouparnadas** [comment]
This has been fixed.

**Comment by mayank2k2** [comment]
This is not working correctly. 
I promoted 5 students in School 'Mayank School' from Class 3 G (Roll number 56-60) to Class 4 B.

I search with for School 'Mayank School' and roll number 56
1 student display with roll number 56 with class three with section G

I search with for School 'Mayank School' and roll number 56 and class three with section G
1 student display with roll number 56 with class three with section G

I search with for School 'Mayank School' and roll number 56 and class four
1 student display with roll number 56 with class four with section G

I search with for School 'Mayank School' and roll number 56 and class four with section B
1 student display with roll number 56 with class four with section B

Please validate.

**Comment by manasghosh81** [comment]
As discussed, Mayank to check this with fresh school and get back to TCS if issue still persists.

**Comment by mayank2k2** [comment]
This is not working

**Comment by mayank2k2** [comment]
also i do not see how to export all student data for promotions to next classes as school admin, we discuss this in FSD reivew

**Comment by manasghosh81** [comment]
I have asked Manas to talk to you and do a webex to see the process being followed for student promotion as it is absolutely working on our side.

Regards
Subha

**Comment by mayank2k2** [comment]
seems working as of now will re-open if find any issue
