### ISSUE TITLE
Corrections in Upload User Template - Instructions

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#49]
Please see attached image for corrections.

![instructions sheet](https://cloud.githubusercontent.com/assets/16831643/12908458/a990c4c8-cf1d-11e5-8c2f-ba62ef68cdce.png)

**Comment by mouparnadas** [comment]
The excel template has been updated and the change will be available in next deployment.

**Comment by kirti-sharma** [comment]
Please see corrections in the screenshot
![instructions sheet](https://cloud.githubusercontent.com/assets/16831643/13071597/854b3812-d4ba-11e5-8bdc-7ffba591da22.png)

**Comment by mayank2k2** [comment]
Please test.

**Comment by kirti-sharma** [comment]
Suggested changes not visible after retest.

**Comment by mouparnadas** [comment]
Updated the bulk upload excel as per comments given by Kirti date 19/2
Also this is updated to make the address fields as blank

**Comment by kirti-sharma** [comment]
Bulk upload sheet has been updated but error messages still have errors (typos and missing punctuation). Corrected error message  sheet has bee shared with Manas on 15 Feb.

Below are a few instances:
Error: Subscription count exceeded. Current **Subcription** count is 0.          (typo)
Error: Email cannot be null             (full stop missing)

**Comment by mouparnadas** [comment]
@kirti-sharma , 
We have corrected the error messages and the punctuations.
Please review and close the bug.

**Comment by madhumitadey** [comment]
Hello, 

The error messages aren't fully corrected as per the excel provided. There are instances where we could still see problems. Screenshots are provided below for your reference.

![error messges in bulk upload](https://cloud.githubusercontent.com/assets/16831474/13518715/d2f348a4-e1f6-11e5-86da-19cbc053581f.png)

I am attaching the excel report. Kindly refer to the report and make changes in the error messages as per the feedback provided.
[Error Messages.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/158155/Error.Messages.xlsx)

**Comment by madhumitadey** [comment]
With reference to #135 , we could still see discrepancies in the final output. The same has been marked for individual cases.

Please refer to screenshots below and make corrections.

![1](https://cloud.githubusercontent.com/assets/16831474/13660549/1fdd05a6-e6b1-11e5-8834-d4af951b3b84.png)
![2](https://cloud.githubusercontent.com/assets/16831474/13660550/1fdf078e-e6b1-11e5-9513-068c33c0b8a3.png)
![3](https://cloud.githubusercontent.com/assets/16831474/13660551/1fe98e16-e6b1-11e5-9020-336786a6173b.png)
![image](https://cloud.githubusercontent.com/assets/16831474/13660664/223357b4-e6b2-11e5-9288-697418a72510.png)

**Comment by manasghosh81** [comment]
The error messages have been modified according to modified error messages provided on 10/03

**Comment by mayank2k2** [comment]
@kirti-sharma  can you review this

**Comment by kirti-sharma** [comment]
Yes... in process.

**Comment by kirti-sharma** [comment]
Fixed.
