### ISSUE TITLE
Search/Advance: Usability issue

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#6]
Issue 1: Control water mark text should be lighter
Expected: Control water mark text should be lighter as per industry standard

Issue 2: Control text font color and watermark text font color is same, there is no difference
Expected: Control water mark text should be lighter so that text can be easily differentiated

Issue 3: if we selected predefined value control looks differently.
Expected: Control background color should not change
[Usability issue.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/115372/Usability.issue.docx)

**Comment by manasghosh81** [comment]
This issue is fixed now and available in UAT for retest.

**Comment by mayank2k2** [comment]
The issue still not fixed combo box still have issues, see the Advance search: select school drop down

**Comment by mayank2k2** [comment]
The issue still not fixed combo box still have issues, see the Advance search: select school drop down

**Comment by mayank2k2** [comment]
Issue still not fixed see 
![issue 6](https://cloud.githubusercontent.com/assets/16239450/13074779/cb154632-d4cc-11e5-89ea-ee2f4da820f0.JPG)

**Comment by manasghosh81** [comment]
Hi Mayank. This is Subha. This cannot be done. The watermark within the textboxes are placeholders and the colour can be changed, however the ones on the dropdowns are actual text as this dropdown is custom made by ui/li. If we change the text colour, all the options within this will change.

**Comment by mayank2k2** [comment]
see the issue tested today 19/2
![usability issue 6](https://cloud.githubusercontent.com/assets/16239450/13166600/95690648-d6ef-11e5-85ec-ef0eb76e81c3.JPG)

**Comment by mouparnadas** [comment]
This is now fixed.

**Comment by mayank2k2** [comment]
working fine
