### ISSUE TITLE
Upload Action keep processing for 30 students upload

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#9]
Step 1: Login with admin user, search school "test school 11"
Step 2: click on upload /validate single student
Step 3: After "No Error" status Click on upload link 

Issue: Upload Action keep processing
Expected : It should show "Processed" status

![upload action keep processing for single student upload](https://cloud.githubusercontent.com/assets/16239450/12806668/fd93203c-cb2d-11e5-97d9-91db06a9ca6c.JPG)

**Comment by manasghosh81** [comment]
This is fixed and will be available in next deployment.

**Comment by mayank2k2** [comment]
working now

**Comment by mayank2k2** [comment]
This is not fixed and taking too much time on uploading 4 records

**Comment by manasghosh81** [comment]
This is fixed, please check.

**Comment by mayank2k2** [comment]
working fine

**Comment by mayank2k2** [comment]
@manasghosh81: Today i uploaded 30 student for new school i have created and it is taking more than 5 minutes and processing still continue.
see the screen shot

![image](https://cloud.githubusercontent.com/assets/16239450/14948228/ad61ebb6-105b-11e6-8f9d-2d3435e0cc94.png)

**Comment by mayank2k2** [comment]
@manasghosh81  still continue processing after 10 minutes:

![image](https://cloud.githubusercontent.com/assets/16239450/14948268/06730302-105c-11e6-9276-0e649893091f.png)

**Comment by mayank2k2** [comment]
only 3 student uploaded where are rest student ???
![image](https://cloud.githubusercontent.com/assets/16239450/14948533/f64d987c-105e-11e6-8c89-babae1caf0ba.png)

**Comment by mayank2k2** [comment]
close the issue and open in production
